def cargar_clubes():
  """
    Carga la información inicial de los clubes de la Liga Profesional
    y de la Primera Nacional.

    Devuelve:
        liga_argentina: lista de diccionarios con los clubes de Primera División.
        primera_nacional: lista de diccionarios con los clubes de Primera Nacional.
  """
    
    
  liga_argentina = [
    {
      "id": 1,
      "club": "Club Atlético Aldosivi",
      "valor_plantel_millones_eur": 8.5,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 2
    },
    {
      "id": 2,
      "club": "Asociación Atlética Argentinos Juniors",
      "valor_plantel_millones_eur": 28.0,
      "titulos_nacionales": 3,
      "titulos_internacionales": 2,
      "copa_libertadores": 1,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 5,
      "descensos": 5
    },
    {
      "id": 3,
      "club": "Club Atlético Tucumán",
      "valor_plantel_millones_eur": 14.0,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 1
    },
    {
      "id": 4,
      "club": "Club Atlético Banfield",
      "valor_plantel_millones_eur": 17.0,
      "titulos_nacionales": 2,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 2,
      "descensos": 8
    },
    {
      "id": 5,
      "club": "Club Atlético Barracas Central",
      "valor_plantel_millones_eur": 11.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 6,
      "club": "Club Atlético Belgrano (Córdoba)",
      "valor_plantel_millones_eur": 21.0,
      "titulos_nacionales": 6,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 6,
      "descensos": 4
    },
    {
      "id": 7,
      "club": "Club Atlético Boca Juniors",
      "valor_plantel_millones_eur": 92.0,
      "titulos_nacionales": 52,
      "titulos_internacionales": 22,
      "copa_libertadores": 6,
      "copa_sudamericana": 2,
      "mundial_de_clubes_intercontinental": 3,
      "titulos_totales": 74,
      "descensos": 0
    },
    {
      "id": 8,
      "club": "Club Atlético Central Córdoba (Santiago del Estero)",
      "valor_plantel_millones_eur": 12.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 9,
      "club": "Club Social y Deportivo Defensa y Justicia",
      "valor_plantel_millones_eur": 18.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 2,
      "copa_libertadores": 0,
      "copa_sudamericana": 1,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 2,
      "descensos": 0
    },
    {
      "id": 10,
      "club": "Club Deportivo Riestra",
      "valor_plantel_millones_eur": 9.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 11,
      "club": "Club Estudiantes de La Plata",
      "valor_plantel_millones_eur": 35.0,
      "titulos_nacionales": 13,
      "titulos_internacionales": 6,
      "copa_libertadores": 4,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 1,
      "titulos_totales": 19,
      "descensos": 2
    },
    {
      "id": 12,
      "club": "Asociación Atlética Estudiantes (Río Cuarto)",
      "valor_plantel_millones_eur": 7.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 13,
      "club": "Club Atlético Gimnasia y Esgrima (Mendoza)",
      "valor_plantel_millones_eur": 7.5,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 14,
      "club": "Club de Gimnasia y Esgrima La Plata",
      "valor_plantel_millones_eur": 19.0,
      "titulos_nacionales": 2,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 2,
      "descensos": 5
    },
    {
      "id": 15,
      "club": "Club Atlético Huracán",
      "valor_plantel_millones_eur": 24.0,
      "titulos_nacionales": 13,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 13,
      "descensos": 4
    },
    {
      "id": 16,
      "club": "Club Atlético Independiente",
      "valor_plantel_millones_eur": 42.0,
      "titulos_nacionales": 25,
      "titulos_internacionales": 20,
      "copa_libertadores": 7,
      "copa_sudamericana": 2,
      "mundial_de_clubes_intercontinental": 2,
      "titulos_totales": 45,
      "descensos": 1
    },
    {
      "id": 17,
      "club": "Club Sportivo Independiente Rivadavia",
      "valor_plantel_millones_eur": 12.5,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 0
    },
    {
      "id": 18,
      "club": "Instituto Atlético Central Córdoba",
      "valor_plantel_millones_eur": 13.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 3
    },
    {
      "id": 19,
      "club": "Club Atlético Lanús",
      "valor_plantel_millones_eur": 26.0,
      "titulos_nacionales": 4,
      "titulos_internacionales": 3,
      "copa_libertadores": 0,
      "copa_sudamericana": 1,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 7,
      "descensos": 5
    },
    {
      "id": 20,
      "club": "Club Atlético Newell's Old Boys",
      "valor_plantel_millones_eur": 23.0,
      "titulos_nacionales": 9,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 9,
      "descensos": 1
    },
    {
      "id": 21,
      "club": "Club Atlético Platense",
      "valor_plantel_millones_eur": 15.0,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 3
    },
    {
      "id": 22,
      "club": "Racing Club",
      "valor_plantel_millones_eur": 58.0,
      "titulos_nacionales": 33,
      "titulos_internacionales": 7,
      "copa_libertadores": 1,
      "copa_sudamericana": 1,
      "mundial_de_clubes_intercontinental": 1,
      "titulos_totales": 40,
      "descensos": 1
    },
    {
      "id": 23,
      "club": "Club Atlético River Plate",
      "valor_plantel_millones_eur": 115.0,
      "titulos_nacionales": 54,
      "titulos_internacionales": 18,
      "copa_libertadores": 4,
      "copa_sudamericana": 1,
      "mundial_de_clubes_intercontinental": 1,
      "titulos_totales": 72,
      "descensos": 1
    },
    {
      "id": 24,
      "club": "Club Atlético Rosario Central",
      "valor_plantel_millones_eur": 29.0,
      "titulos_nacionales": 12,
      "titulos_internacionales": 1,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 13,
      "descensos": 4
    },
    {
      "id": 25,
      "club": "Club Atlético San Lorenzo de Almagro",
      "valor_plantel_millones_eur": 38.0,
      "titulos_nacionales": 17,
      "titulos_internacionales": 5,
      "copa_libertadores": 1,
      "copa_sudamericana": 1,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 22,
      "descensos": 1
    },
    {
      "id": 26,
      "club": "Club Atlético Sarmiento (Junín)",
      "valor_plantel_millones_eur": 10.5,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 2
    },
    {
      "id": 27,
      "club": "Club Atlético Talleres (Córdoba)",
      "valor_plantel_millones_eur": 45.0,
      "titulos_nacionales": 1,
      "titulos_internacionales": 1,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 2,
      "descensos": 2
    },
    {
      "id": 28,
      "club": "Club Atlético Tigre",
      "valor_plantel_millones_eur": 16.0,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 8
    },
    {
      "id": 29,
      "club": "Club Atlético Unión (Santa Fe)",
      "valor_plantel_millones_eur": 16.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 5
    },
    {
      "id": 30,
      "club": "Club Atlético Vélez Sarsfield",
      "valor_plantel_millones_eur": 36.0,
      "titulos_nacionales": 14,
      "titulos_internacionales": 5,
      "copa_libertadores": 1,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 1,
      "titulos_totales": 19,
      "descensos": 1
    }
  ]

  primera_nacional = [
    {
      "id": 1,
      "club": "Club Atlético Acassuso",
      "valor_plantel_millones_eur": 1.6,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 2,
      "club": "Club Agropecuario Argentino",
      "valor_plantel_millones_eur": 2.5,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 3,
      "club": "Club Atlético All Boys",
      "valor_plantel_millones_eur": 3.4,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 2
    },
    {
      "id": 4,
      "club": "Club Almagro",
      "valor_plantel_millones_eur": 2.6,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 3
    },
    {
      "id": 5,
      "club": "Club Almirante Brown",
      "valor_plantel_millones_eur": 2.9,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 6,
      "club": "Club Atlético Atlanta",
      "valor_plantel_millones_eur": 3.8,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 4
    },
    {
      "id": 7,
      "club": "Club Atlético de Rafaela",
      "valor_plantel_millones_eur": 3.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 2
    },
    {
      "id": 8,
      "club": "Club Central Norte (Salta)",
      "valor_plantel_millones_eur": 2.1,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 9,
      "club": "Club Atlético Chacarita Juniors",
      "valor_plantel_millones_eur": 4.5,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 7
    },
    {
      "id": 10,
      "club": "Club Atlético Chaco For Ever",
      "valor_plantel_millones_eur": 2.4,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 11,
      "club": "Club Ciudad de Bolívar",
      "valor_plantel_millones_eur": 1.7,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 12,
      "club": "Club Atlético Colegiales",
      "valor_plantel_millones_eur": 1.9,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 13,
      "club": "Club Atlético Colón",
      "valor_plantel_millones_eur": 7.5,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 4
    },
    {
      "id": 14,
      "club": "Club Atlético Defensores de Belgrano",
      "valor_plantel_millones_eur": 3.2,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 15,
      "club": "Club Social y Deportivo Madryn",
      "valor_plantel_millones_eur": 2.7,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 16,
      "club": "Club Deportivo Maipú",
      "valor_plantel_millones_eur": 2.8,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 17,
      "club": "Club Deportivo Morón",
      "valor_plantel_millones_eur": 2.9,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 18,
      "club": "Club Atlético Estudiantes (Buenos Aires)",
      "valor_plantel_millones_eur": 3.3,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 3
    },
    {
      "id": 19,
      "club": "Club Ferro Carril Oeste",
      "valor_plantel_millones_eur": 4.8,
      "titulos_nacionales": 2,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 2,
      "descensos": 6
    },
    {
      "id": 20,
      "club": "Club Atlético Gimnasia y Esgrima (Jujuy)",
      "valor_plantel_millones_eur": 3.1,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 2
    },
    {
      "id": 21,
      "club": "Club de Gimnasia y Tiro (Salta)",
      "valor_plantel_millones_eur": 2.5,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 2
    },
    {
      "id": 22,
      "club": "Club Deportivo Godoy Cruz Antonio Tomba",
      "valor_plantel_millones_eur": 10.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 2
    },
    {
      "id": 23,
      "club": "Club Atlético Güemes",
      "valor_plantel_millones_eur": 2.2,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 24,
      "club": "Club Atlético Los Andes",
      "valor_plantel_millones_eur": 2.8,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 3
    },
    {
      "id": 25,
      "club": "Club Atlético Ferrocarril Midland",
      "valor_plantel_millones_eur": 1.7,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 26,
      "club": "Club Atlético Mitre (Santiago del Estero)",
      "valor_plantel_millones_eur": 2.6,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 27,
      "club": "Club Atlético Nueva Chicago",
      "valor_plantel_millones_eur": 3.7,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 4
    },
    {
      "id": 28,
      "club": "Club Atlético Patronato",
      "valor_plantel_millones_eur": 3.9,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 1
    },
    {
      "id": 29,
      "club": "Quilmes Atlético Club",
      "valor_plantel_millones_eur": 5.2,
      "titulos_nacionales": 3,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 3,
      "descensos": 11
    },
    {
      "id": 30,
      "club": "Club Atlético Racing (Córdoba)",
      "valor_plantel_millones_eur": 2.7,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 31,
      "club": "Club Atlético San Martín (San Juan)",
      "valor_plantel_millones_eur": 4.2,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 3
    },
    {
      "id": 32,
      "club": "Club Atlético San Martín (Tucumán)",
      "valor_plantel_millones_eur": 4.6,
      "titulos_nacionales": 1,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 1,
      "descensos": 4
    },
    {
      "id": 33,
      "club": "Club Atlético San Miguel",
      "valor_plantel_millones_eur": 3.0,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    },
    {
      "id": 34,
      "club": "Club Atlético San Telmo",
      "valor_plantel_millones_eur": 2.9,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 1
    },
    {
      "id": 35,
      "club": "Club Atlético Temperley",
      "valor_plantel_millones_eur": 3.5,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 3
    },
    {
      "id": 36,
      "club": "Club Social y Deportivo Tristán Suárez",
      "valor_plantel_millones_eur": 2.5,
      "titulos_nacionales": 0,
      "titulos_internacionales": 0,
      "copa_libertadores": 0,
      "copa_sudamericana": 0,
      "mundial_de_clubes_intercontinental": 0,
      "titulos_totales": 0,
      "descensos": 0
    }
  ]


  return liga_argentina, primera_nacional